### ISSUE TITLE
Northern Tales of the Sword Coast: Svlast NPC Inter-mod Conflict

### ISSUE THREAD

**Issue by Endarire** [SpellholdStudios/NTotSC#19]
Greetings, jastey!

According to the Big World Setup tool which I used to check inter-mod compatibility, the NPC Svlast from Northern Tales (component 6) conflicts with Svlast from BG1's Unfinished Business mod (component 22).  Can these be reconciled and made compatible?  If so, how should they?

Thankee!

Error Message:
![image](https://user-images.githubusercontent.com/10439725/92425487-47040900-f13c-11ea-8777-a909aa995b9e.png)

**Comment by Gitjas** [comment]
The two components do basically the same, they restore the unused dialogues in the game. The two mods are as compatible as they can be: if one is installed, the other one will be skipped.

**Comment by Endarire** [comment]
Thankee!
