### ISSUE TITLE
Issues with equipped slots for ntmariel.cre and ntogremu.cre 

### ISSUE THREAD

**Issue by TotoR115** [SpellholdStudios/NTotSC#38]
There is 2 bugs with references for creature's equipment slots :

- ntmariel.cre - armor is not equipped, sword is placed in armor slot, etc... (references start at 1 instead of 0)

- ntogremu.cre - is equipped with an unexistent weapon (1) instead of the STAF23.ITM (Serpent Shaft +3) (0)

**Comment by Gitjas** [comment]
Thanks! Fixed locally.
