### ISSUE TITLE
Improved Lesser Fiends Component : missing scripts

### ISSUE THREAD

**Issue by TotoR115** [SpellholdStudios/NTotSC#42]
@AngelGryph, the component `Improved Lesser Fiends` does not install the new dedicated scripts for fiends:

- ntfiends.baf
- ntmaurez.baf
- ntsuccub.baf

**Comment by AngelGryph** [comment]
Yep, looks like I made an oversight when changing script names.  Will fix, thanks for the report.

**Comment by Gitjas** [comment]
Turns out I can't fix this because I don't undestand what the function is doing. :-(

**Comment by AngelGryph** [comment]
I already fixed this one on my branch.  I wanted to wait until I have more to add, but I can make a pull request now if you really want to have it.

**Comment by Gitjas** [comment]
I'm preparing a new version, so I'd take anything I can get. :-) Unless you think a new version now wouldn't make sense without your further input.
I checked your fork but didn't see a fix, seems I'm not really versed with GitHub.

**Comment by Gitjas** [comment]
No rush, though. I just figured I'd have to update the readme, too. These things usually take more time.

**Comment by AngelGryph** [comment]
I haven't pushed them yet, they are local on my machine.  I'll run some quick tests and get them out ASAP.

I wanted to do more testing and fine-tuning on the tactical components, but I never seem to get to it.  I have so much stuff to test and go through on my next BG1 run.  They do work on a basic level though.

**Comment by Gitjas** [comment]
Cool! Would you include a short blurb about what the new components are doing, nothing detailed just a one-liner for each for the readme description?

**Comment by Gitjas** [comment]
I meant anything more detailed than "this component improves the fight with [insert foe name]" in case it makes sense. :-)

**Comment by AngelGryph** [comment]
Done.  I did quick tests and everything installs cleanly on BGEE and BGT.
