### ISSUE TITLE
Tiny Typo #1

### ISSUE THREAD

**Issue by TotoR115** [SpellholdStudios/NTotSC#52]
There is a Typo:
https://github.com/SpellholdStudios/NTotSC/blob/c06414ee1d3733547dcfd8d470d09410aea0a95b/ntotsc/modify/dlg/lamalh.d#L2

Should be `NTNATALK` instead of `NATALKA`

**Comment by TotoR115** [comment]
https://github.com/SpellholdStudios/NTotSC/blob/c06414ee1d3733547dcfd8d470d09410aea0a95b/ntotsc/ntotsc.tp2#L361
To prevent this, some items need to be added to itemexcl.2da: 
```
COPY_EXISTING ~itemexcl.2da~ ~override~
    APPEND ~itemexcl.2da~ ~NTPLAT01  1~
    APPEND ~itemexcl.2da~ ~NTPLAT02  1~
    APPEND ~itemexcl.2da~ ~NTPLAT03  1~
    APPEND ~itemexcl.2da~ ~NTPLAT04  1~
    APPEND ~itemexcl.2da~ ~NTCHAN06  1~
    APPEND ~itemexcl.2da~ ~NTLEAT05  1~
    APPEND ~itemexcl.2da~ ~NTRING02 1~
    APPEND ~itemexcl.2da~ ~NTROBE01 1~
    APPEND ~itemexcl.2da~ ~NTROBE02 1~
```
In addition, the following items are missing there enchantement level:
```
ntplat01.itm is lv 1
ntplat02.itm is lv 2
ntplat03.itm is lv 2
ntplat04.itm is lv 1
ntchan06.itm is lv 1
ntleat05.itm is lv 2
ntring04.itm is lv 1
```

Lastly ntplat02 witch is a full plate as description as wrong AC. for a +2 it should be -1 instead of actual 0 (or the plate should be a +1 only)

**Comment by Roberciiik** [comment]
> Lastly ntplat02 witch is a full plate as description as wrong AC. for a +2 it should be -1 instead of actual 0 (or the plate should be a +1 only)

I believe it supposes to be a field armor which is something between a plate armor and a full plate armor. It is nerfed from full plate. Enhancement +2 still applies.

**Comment by TotoR115** [comment]
> I believe it supposes to be a field armor

Ok, in this case, the name could be updated:
`Ghotal's Full Plate +2` for `Ghotal's Field Plate +2`

**Comment by Roberciiik** [comment]
Correct! Here is the change: [Item Rebalancing](https://github.com/SpellholdStudios/NTotSC/commit/901fd5699d5f0ce5cd98e572540f472c8dbdb239), as you can see description is updated but not the armor name.

**Comment by TotoR115** [comment]
another small bug :

- ntbow04.itm has a wrong icon at 0x76 (item ability) : iclbhand.bam instead of ntbow04.bam

**Comment by AngelGryph** [comment]
Good catches, will fix.

**Comment by ALIENQuake** [comment]
@AngelGryph So this issue can now be closed?

**Comment by AngelGryph** [comment]
Yes, these should all be fixed in the master.
