### ISSUE TITLE
Some traps can't be detected or disarmed

### ISSUE THREAD

**Issue by AngelGryph** [SpellholdStudios/NTotSC#6]
My thief has 135% Detect/Remove traps, and still cannot detect or disarm some of the traps encountered.

**Comment by Gitjas** [comment]
New version is up and I nerfed some traps:
-AR82PB.are, Container0 ("Bookshelf"): fall detection changed to 90, trap removal to 101
-Krotan's crypt (AR34PB.are): removed trap at the entrance and changed one of the other ones to "miscast Magic" trap.
-Haeball (AR9001, AR9002): traps on containers changed to 90/90. Trap in cellar is removable for 101
-Temple of the Black Hand (AR61PB): removed arrows of detonation from cultist archers. Moved trap with fireball away from entrance point
