### ISSUE TITLE
Sealed crypt battle too hardcore

### ISSUE THREAD

**Issue by AngelGryph** [SpellholdStudios/NTotSC#7]
The battle in the sealed crypt isn't winnable even with a fully buffed endgame party that can take on Sarevok or Aec'letec with no trouble; the knights are too hardcore.  Also another unavoidable trap right at the entrance.

**Comment by Gitjas** [comment]
Thank you very much for all the feedback and reports. I'll definitely rework most of the traps to make them at least detectable. All things are noted and I will look into them.

**Comment by AngelGryph** [comment]
Glad to hear it.  I really like this mod, but it does have a couple of rough edges here and there.

**Comment by AngelGryph** [comment]
Mm, I am currently a little busy with an item pack mod I intend to publish soon, but I could perhaps lend a hand here and there if you'd like.  I'm familiar with 2E rules and good with numbers, I can probably make sure the enemies at least have a level-appropriate thac0 and AC.  I'm also pretty handy with editing items, I can fix the monk permissions and the missing icon of the bow.  Let me know if you want my help.  You can also reach me on G3 (Angel) or SHS (MadeInHeaven), or if you like on Discord (Angel#8798).

**Comment by Gitjas** [comment]
Your help would be very appreciated! This would be very awesome, not only because it would spare me work (heh) but because that's the things I am not good at (like, at all).

**Comment by AngelGryph** [comment]
Alright, I'll create a fork and try to get some fixes done.  I probably can have the item issues done sometime this week, maybe even tonight.  Fight balancing may take a little longer though.

**Comment by Gitjas** [comment]
Have a look here: https://www.baldurs-gate.de/index.php?threads/ntotsc-f%C3%BCr-bgt-bg-ee-und-eet.44467/page-7#post-1073489

Dachrisma identified those items to be not used in the game, so those will be deleted in the next update.

**Comment by AngelGryph** [comment]
My German is a little rusty, but I think I get the gist of that thread.  Alright, I'll take those out.  Saves a lot of work.  Some of them seem to already be gone in the copy I have.

I might also restore a few items while I am at it, judging by some comments in the code it used to introduce some items from IWD, like the Black Swan Armor.  That's something I can definitely do.  But, one thing at a time or I overwhelm myself. :-)

**Comment by Gitjas** [comment]
I'll look foreward to your changes. Take all the time you want!

**Comment by Gitjas** [comment]
Angel, just a note: please keep in mind that the items are supposed to work on BGT, i.e. classic engine, as well. Best to work on that engine, because backwards compatibility from the EE is not guaranteed.

Also, there is one thing I am sure is connected to an item but I was unable to identify the source of the problem: in AR9001 NTHAEBAL.cre always gets 3 damage when PC enters the area (i.e. the area is loaded).

**Comment by AngelGryph** [comment]
No worries there, I still have a BGT installation I use for testing and that's where I did the edits (except for ar20pb.are because that problem was specitfic to BGEE).  Besides, the .itm format did not change in a major way between BG2 and BGEE, usuability flags still work exactly the same.  (The only change is that some previously unused fields now actually do something.)

And yes, I noticed that too and saw the comment about it in the .tp2 file.  I'll see what I can do, it's probably a mistargeted effect on an item.

**Comment by AngelGryph** [comment]
Confirmed, it's a buggy item, ntspear1.itm.  Couple of issues there actually, one of them another BG1 artefact.  I can fix that, it will be in my next pull request.

**Comment by AngelGryph** [comment]
You've been busy I see.  Well I was just about to start a new BG1EE game, I will definitely take these updates along, and see if I can adjust the creature stats on the fly as I fight the battles.  I might do some further item editing as well, I still see some room for improvement there.  (Most of them seem to be lifted straight from IWD1 with minimal editing.)

**Comment by Gitjas** [comment]
Cool! Thank you in advance.
